version: "3.7"
services:
  dev:
    command: tail -f /dev/null # TODO(andy): Less hacky way to do this
    build:
      context: .
      args:
        YARN_FLAGS: ""
        COPY_OWNER: node:node
        DEV_TOOLS: build-base git python openssh-client bash zsh
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules/
      - yarn_cache:/home/node/.cache/yarn/
      - type: bind
        source: ~/.gitconfig
        target: /home/node/.gitconfig
      - type: bind
        source: ~/.ssh/
        target: /home/node/.ssh/
        read_only: true
    ports:
      - "3000:3000"
volumes:
  node_modules:
  yarn_cache:
